config/routes.rb
Rails.application.routes.draw do
  resources :documents do
    post 'sent', on: :collection
    post 'add_receipt', on: :collection
    post 'approved', on: :collection
    post 'extract_text', on: :collection

  end
  resources :immigration_cases
  resources :foreign_nationals
  resources :accounts 
  devise_for :users
  resources :accesses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/search', to: 'application#search', as: :search

  # Defines the root path route ("/")

  root "accounts#index"

end
 

app/models/foreign_national.rb
# == Schema Information
#
# Table name: foreign_nationals
#
#  id         :bigint           not null, primary key
#  address    :string
#  birthday   :date
#  name       :string
#  status     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  account_id :integer
#
class ForeignNational < ApplicationRecord
  validates :name, presence: true
  belongs_to :account, foreign_key: "account_id"
  has_many  :immigration_cases, class_name: "ImmigrationCase", foreign_key: "foreign_nationals_id"

  enum status: {
    "Outside-US": 0,
    Visa: 1,
    Pending: 2,
    Greencard: 3,
    Citizen: 4 # New status value
  }
  def self.ransackable_attributes(auth_object = nil)
    ["account_id", "id", "name"]
  end
  
end

app/controllers/foreign_nationals_controller.rb
class ForeignNationalsController < ApplicationController
  before_action :set_foreign_national, only: %i[ show edit update destroy ]

  # GET /foreign_nationals or /foreign_nationals.json
  def index

    @foreign_nationals = if current_user.admin?
      @q = ForeignNational.ransack(params[:q])
      @ForeignNational = @q.result
    else
      current_user.ForeignNational
    end
    
  end

  # GET /foreign_nationals/1 or /foreign_nationals/1.json
  def show
    @foreign_national = ForeignNational.find(params[:id])
    @foreign_national_id = @foreign_national.id
    @account_id = @foreign_national.account_id
  end

  # GET /foreign_nationals/new
  def new
    @foreign_national = ForeignNational.new
    @account_id = params[:account_id]

    
  end

  # GET /foreign_nationals/1/edit
  def edit
    @account_id = @foreign_national.account_id

  end

  # POST /foreign_nationals or /foreign_nationals.json
  def create
    puts "Params: #{params.inspect}"
    @foreign_national = ForeignNational.new(foreign_national_params)
    @account_id = params[:account_id]
    respond_to do |format|
      if @foreign_national.save
        format.html { redirect_to account_path(@foreign_national.account_id), notice: "Foreign national was successfully created." }
        format.json { render :show, status: :created, location: @foreign_national }
        
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @foreign_national.errors, status: :unprocessable_entity }

      end
    end
  end

  # PATCH/PUT /foreign_nationals/1 or /foreign_nationals/1.json
  def update
    @account_id = @foreign_national.account_id
    respond_to do |format|
      if @foreign_national.update(foreign_national_params)
        format.html { redirect_to foreign_national_url(@foreign_national), notice: "Foreign national was successfully updated." }
        format.json { render :show, status: :ok, location: @foreign_national }
      else
        flash.now[:alert] = "Error updating foreign national. Please check the form."

        format.html { render :show, status: :unprocessable_entity }
        format.json { render json: @foreign_national.errors, status: :unprocessable_entity }
  
      end
    end
  end
  

  # DELETE /foreign_nationals/1 or /foreign_nationals/1.json
  def destroy 
    account_id = @foreign_national.account.id

    @foreign_national.immigration_cases.each do |immigration_case|
      immigration_case.document.each do |doc|
        doc.destroy
      end

      immigration_case.destroy

    end
    @foreign_national.destroy
    respond_to do |format|
      format.html { redirect_to account_path(account_id), notice: "Foreign national was successfully destroyed." }
      format.json { head :no_content }
    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foreign_national
      @foreign_national = ForeignNational.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def foreign_national_params
      params.require(:foreign_national).permit(:name, :status, :birthday, :address, :account_id)
    end
end

app/views/foreign_nationals/_edit.html.erb
<div class="modal fade" id="foreignNationalEditModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edit Foreign National</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
<%= render "form", foreign_national: @foreign_national, account_id: @foreign_national.account_id%>       
      </div>
    </div>
  </div>
</div>

app/views/foreign_nationals/_foreign_national.html.erb
<div id="<%= dom_id foreign_national %>">
  <p>
    <strong>Name:</strong>
    <%= foreign_national.name %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= foreign_national.status %>
  </p>

  <p>
    <strong>Birthday:</strong>
    <%= foreign_national.birthday %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= foreign_national.address %>
  </p>

</div>

app/views/foreign_nationals/_foreign_nationals_cases.html.erb
<% foreign_national.immigration_cases.each do |immigration_case|%>
  <div class="card">
    <div class="card-header position-relative" style="transition: background-color 0.3s ease; background-color: #fff;" onmouseover="this.style.backgroundColor='rgba(89, 7, 162, .7)'" onmouseout="this.style.backgroundColor='#fff'">   
      <strong style= " margin-left: 15px;">
        <%= link_to immigration_case.case_type, immigration_case_path(immigration_case.id), class: "stretched-link", style: "color: inherit; text-decoration: none;  font-size: 18px;"  %>
      </strong>
    </div>
    <div class="card-body" style="text-align: center;">
      <h6 class="card-title">Case Status</h6>

    </div>
    
  
  </div>
<% end %>

app/views/foreign_nationals/_foreign_nationals_profile.html.erb
<div id="<%= dom_id foreign_national %>">
  <p>
    <strong>Name:</strong>
    <%= @foreign_national.name %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= @foreign_national.status %>
  </p>

  <p>
    <strong>Birthday:</strong>
    <%= @foreign_national.birthday %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= @foreign_national.address %>
  </p>
  <hr>
  <%@foreign_national.immigration_cases.each do |c|%>
  <p>
    <strong>
      <span style="display: inline-block; margin-right: 10px;"><%=c.case_type%></span>
      <span style="display: inline-block;"><%= c.status%></span>
    </strong>
   </p>
    <% if ImmigrationCase.statuses[c.status] >= 2 %>
      <p>
        <strong>
          Sent Date: 
        </strong>
        <%= c.sent_date%>
      </p>
    <% end %>
    <% if ImmigrationCase.statuses[c.status] >= 3 %>
      <p>
        <strong>
          Received Date: 
        </strong>
        <%= c.received_date%>
      </p>

      <p>
        <strong>
          Receipt Number: 
        </strong>
        <%= c.receipt_number%>
      </p>
    <% end %>
    <% if ImmigrationCase.statuses[c.status] == 5 %>
      <p>
        <strong>
          Approval Date: 
        </strong>
        <%= c.approval_date%>
      </p>
      <p>
        <strong>
          Expiration Date: 
        </strong>
        <%= c.expiration_date%>
      </p>
    <% end %>
    <hr>
  <% end %>

</div>

app/views/foreign_nationals/_foreign_nationals_side_button.html.erb
<div class="position-fixed bottom-0 start-0">
  <button class="btn btn-light" id="dropdownUser3" data-bs-toggle="dropdown" aria-expanded="false" style="background-color: #9205C4">
    <i class="bi bi-power bi-3x"></i>
  </button>
  <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser3">

  <li>
  <%= link_to "Edit this foreign national", edit_foreign_national_path(@foreign_national), class: "dropdown-item", data: { toggle: "modal", target: "#foreignNationalEditModal" } %>
</li>
  <li>
  <%= link_to "Back to Account", account_path(@foreign_national.account.id), class: "dropdown-item" %>
</li>
    <li><hr class="dropdown-divider"></li>
    <li>
      <%= button_to "Destroy this foreign national", @foreign_national, method: :delete,  class: "dropdown-item", style: "color: #FD0404" %>
    </li>
  </ul>

</div>

<%= render "foreign_nationals/edit" %>

app/views/foreign_nationals/_form.html.erb
<%= form_with(model: foreign_national, class: "needs-validation", novalidate: true) do |form| %>
  <% if foreign_national.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading">Validation Error!</h4>
      <ul>
        <% foreign_national.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :status, "Select Status", class: "form-label" %>
    <%= form.select :status, ForeignNational.statuses.keys, { include_blank: "Select a Status" }, class: "form-select", required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :birthday, class: "form-label" %>
    <%= form.date_field :birthday, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :address, class: "form-label" %>
    <%= form.text_field :address, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= form.hidden_field :account_id, value: @account_id %>
  </div>

  <div class="mb-3">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/foreign_nationals/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Foreign nationals</h1>

<div id="foreign_nationals">
  <% @foreign_nationals.each do |foreign_national| %>
    <%= render foreign_national %>
    <p>
      <%= link_to "Show this foreign national", foreign_national %>
    </p>
  <% end %>
</div>

<%= link_to "New foreign national", new_foreign_national_path %>

app/views/foreign_nationals/new.html.erb
<h1>New foreign national</h1>

<%= render "form", foreign_national: @foreign_national %>

<br>

<div>
  <%= link_to "Back to foreign nationals", foreign_nationals_path %>
</div>

app/views/foreign_nationals/show.html.erb
<div class="d-flex">
  <div class="col-md-10 offset-md-1">

    <div class="form-check form-switch">
      <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault">
      <label class="form-check-label" for="flexSwitchCheckDefault" id="toggleLabel">Toggle Profile</label>
    </div>

    <div id="profile" class="page-content">
      <!-- Cases page -->
      <div class="d-flex justify-content-between align-items-baseline">
        <h1><%= @foreign_national.name.capitalize() %>'s Cases</h1>
        <!-- i know its cluttered... -->
        <!-- But this modal toggles new_case modal in shared that loads an immigration case form-->
        <%= link_to "#", 
          data: { toggle: "modal", target: "#ImmigrationCaseModal#{@foreign_national.id}", fn: @foreign_national }, 
          class: "btn btn-light ms-2", 
          style: "width: 40px; text-decoration: none; color: #000;",
          onmouseover: "this.style.backgroundColor='#9205C4';",
          onmouseout: "this.style.backgroundColor='transparent';" do %>
          <i class="fas fa-plus-square"></i>
        <% end %>
      </div>
      <%= render "shared/new_case", fn: @foreign_national_id %>
      <hr>
      <% @foreign_national.immigration_cases.each do |immigration_case|%>
        <%= render "shared/cases", immigration_case: immigration_case%>
        <br>
      <% end %>
    </div>

    <div id="cases" class="page-content" style="display: none;">
      <!-- Profile page with details -->
      <h1><%= @foreign_national.name %>'s Profile</h1>
      <%= render "foreign_nationals_profile", foreign_national: @foreign_national%>

    </div>

  </div>
</div>

<%= render "foreign_nationals_side_button"%>

<script>
  $(document).ready(function () {
    $('#flexSwitchCheckDefault').change(function () {
      if (this.checked) {
        $('#profile').hide();
        $('#cases').show();
        $('#toggleLabel').text('Toggle Cases');
      } else {
        $('#profile').show();
        $('#cases').hide();
        $('#toggleLabel').text('Toggle Profile');
      }
    });
  });
</script>