config/routes.rb
Rails.application.routes.draw do
  resources :documents do
    post 'sent', on: :collection
    post 'add_receipt', on: :collection
    post 'approved', on: :collection
    post 'extract_text', on: :collection

  end
  resources :immigration_cases
  resources :foreign_nationals
  resources :accounts 
  devise_for :users
  resources :accesses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/search', to: 'application#search', as: :search

  # Defines the root path route ("/")

  root "accounts#index"

end
 

app/views/shared/_cases.html.erb
<div class="card">
  <div class="card-header position-relative" style="transition: background-color 0.3s ease; background-color: #fff;" onmouseover="this.style.backgroundColor='rgba(89, 7, 162, .7)'" onmouseout="this.style.backgroundColor='#fff'">    <strong style= " margin-left: 15px;">
      <%= link_to immigration_case.case_type, immigration_case_path(immigration_case.id), class: "stretched-link", style: "color: inherit; text-decoration: none;  font-size: 18px;"  %>
    </strong>
  </div>
  <div class="card-body" style="text-align: center;">
    <h6 class="card-title">Case Status</h6>
    <%= render 'shared/status_bar', immigration_case: immigration_case%>

  </div>
</div>

app/views/shared/_cdn_assets.html.erb
<!-- Connect Bootstrap CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css">
<!-- Connect Bootstrap JavaScript and its dependencies -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" > 


<!-- Connect Font Awesome -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/js/all.min.js"></script>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


</body>

app/views/shared/_flash.html.erb
<div class="alert alert-<%= css_class %> alert-dismissible fade show" role="alert">
  <%= message %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar ", style="background-color: #5907A2;">

  <div class="container">
    <a class="navbar-brand" href="<%= root_path %>" style="color: #FF7102; font-size: 24px;" ><strong>Project Y</strong></a>

    <!-- search bar -->
    
<%= search_form_for @q, url: search_path, method: :get, html: { class: "form-inline my-2 my-lg-0 justify-content-center mx-auto" } do |f| %>

    <form class="form-inline my-2 my-lg-0 justify-content-center mx-auto">
      <div class="input-group">
  <%= f.search_field :name_cont, class: "form-control", placeholder: "Search", aria_label: "Search", size: 60 %>
        <div class="input-group-append">
  <button class="btn btn-success my-2 my-sm-0" type="submit">Search</button>
        </div>
      </div>
    </form>
    <% end %>
  </div>

  <!--Collapsable element-->

  <div style="text-align: right; padding-right: 10px;">
    <button class="navbar-toggler"  type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation" >
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>

<div class="collapse-vertical collapse"  id="navbarToggleExternalContent" style="text-align: right; padding: 10px; background-color: #9205C4;">
  <%if current_user != nil %>

    <%= link_to "Edit User", edit_user_registration_path , class: "nav-link"%>

    <%if current_user.admin == true%>
      <%= link_to "New access", new_access_path, class:"nav-link"%>

      <%= link_to "Create account", new_account_path, class: "nav-link" %>
    <%end%>
    <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %>
  <% else %>
    <p>
      The information provided on this website does not, and is not intended to, constitute legal advice; instead, all information, content, and materials available on this site are for general informational purposes only. </p>
  <% end %>
</div>

app/views/shared/_new_case.html.erb
<!-- Modal -->
<div class="modal fade" id="ImmigrationCaseModal<%=fn%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add New Case</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      
    
        <%= render 'immigration_cases/form', immigration_case: ImmigrationCase.new, foreign_nationals_id: fn%>
        
      </div>
    </div>
  </div>
</div>
 

app/views/shared/_searchbar.html.erb
<%= search_form_for @q do |f| %>
  <%= f.label :name_cont, 'Name contains' %>
  <%= f.search_field :name_cont %>

  <%= f.submit 'Search' %>
<% end %>

app/views/shared/_sidebutton.html.erb
<div class="position-fixed bottom-0 start-0">
  <button class="btn btn-light" id="dropdownUser3" data-bs-toggle="dropdown" aria-expanded="false" style="background-color: #9205C4">
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-power" viewBox="0 0 16 16">
      <path d="M7.5 1v7h1V1h-1z"/>
      <path d="M3 8.812a4.999 4.999 0 0 1 2.578-4.375l-.485-.874A6 6 0 1 0 11 3.616l-.501.865A5 5 0 1 1 3 8.812z"/>
    </svg>
  </button>
  <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser3">
    <li><a class="dropdown-item" href="#">New FN</a></li>
    <li><a class="dropdown-item" href="#">Settings</a></li>
    <li><a class="dropdown-item" href="#">Profile</a></li>
    <li><hr class="dropdown-divider"></li>
    <li><a class="dropdown-item" href="#">Sign out</a></li>
  </ul>
</div>

app/views/shared/_status_bar.html.erb
<% if immigration_case.status != nil %>
  <ul class="steps">
    <% (ImmigrationCase.statuses.length - 1).times do |index|%>
      <% if index < ImmigrationCase.statuses[immigration_case.status] %>
        <li class="step step-success">
      <% elsif index == ImmigrationCase.statuses[immigration_case.status] %>
        <li class="step step-active">
      <% else %>
        <li class="step">
      <% end %>
        <div class="step-content">
            <span class="step-circle"><i class="fa-solid fa-check"></i></span>
            <span class="step-text"><%= ImmigrationCase.statuses.keys[index] %></span>
        </div>
        </li>
    <% end %>
  </ul>
<% end %>

app/views/shared/search.html.erb
<div class="row" style="margin: 0 auto;">
  <% @results.each do |result| %>
    <div class="col mx-auto" style="margin: 20px; display: flex; justify-content: space-around;">
      <div class="card" style="width: 18rem;">
        <div class="card-header" style="display: flex; justify-content: space-between;">
          <span><%= result.name %></span>
          <span>ID: <%= result.id %></span>
        </div>
        <div class="card-body">
        <% if result.respond_to?(:notes)
 %>
           <p class="card-text"><%= result.notes %></p>
        <% elsif result.respond_to?(:immigration_cases) %>
          <p class="card-text">Case Count: <%= result.immigration_cases.count %></p>
        <% end %>
       
        </div>
        <%= link_to "Show #{result.class}", result, class: "btn", style: "background-color: rgba(89, 7, 162, 0.7);" %>
      </div>
    </div>
  <% end %>
</div>