config/routes.rb
Rails.application.routes.draw do
  resources :documents do
    post 'sent', on: :collection
    post 'add_receipt', on: :collection
    post 'approved', on: :collection
    post 'extract_text', on: :collection

  end
  resources :immigration_cases
  resources :foreign_nationals
  resources :accounts 
  devise_for :users
  resources :accesses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/search', to: 'application#search', as: :search

  # Defines the root path route ("/")

  root "accounts#index"

end
 

app/models/document.rb
# == Schema Information
#
# Table name: documents
#
#  id                  :bigint           not null, primary key
#  extracted_text      :string
#  image               :string
#  name                :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  immigration_case_id :bigint           not null
#  uploader_id         :bigint           not null
#
# Indexes
#
#  index_documents_on_immigration_case_id  (immigration_case_id)
#  index_documents_on_uploader_id          (uploader_id)
#
# Foreign Keys
#
#  fk_rails_...  (immigration_case_id => immigration_cases.id)
#  fk_rails_...  (uploader_id => users.id)
#
class Document < ApplicationRecord
  # delete commented out code
  #mount_uploader :image, ImageUploader
  mount_uploader :image, ImageUploader

  belongs_to :immigration_case, class_name: "ImmigrationCase"
  belongs_to :uploader, class_name: "User"
  
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: %i[ show edit update destroy ]

  # GET /documents or /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1 or /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents or /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to request.referer || foreign_national_url(params[immigration_case_id]), notice: "Document was successfully created." }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render redirect_to request.referer || foreign_national_url(params[immigration_case_id]), status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # You probably want to move this OCR and text extraction logic to a service for maintainability/readability or even a method on your Document model
  # https://www.toptal.com/ruby-on-rails/rails-service-objects-tutorial
  # https://dev.37signals.com/vanilla-rails-is-plenty/
#pull receipt and date if possible
  def extract_text
    img = RTesseract.new(params[:image].tempfile.path)
  
    begin
      text = img.to_s
      #it just works™️#
      receipt_number_match = text.match(/\n([A-Z]{3}.*?\d{5})\n/)
      notice_date_match = text.match(/\n([A-Za-z]+\s\d{1,2},\s\d{4})\n/)
  
      if receipt_number_match
        extracted_receipt_number = receipt_number_match[1].gsub(" ", "-")
      else
        extracted_receipt_number = "No match for receipt number."
      end
  
      if notice_date_match
        extracted_notice_date = notice_date_match[1]
        extracted_notice_date = Date.strptime(extracted_notice_date, "%b %d, %Y")

      else
        extracted_notice_date = "No match for notice date."
      end
  
    rescue StandardError => e
      extracted_receipt_number = "Error extracting receipt number: #{e.message}"
      extracted_notice_date = "Error extracting notice date: #{e.message}"
    end
  
    render json: { receipt_number: extracted_receipt_number, notice_date: extracted_notice_date }
  end
  
#add sent document and change case status to sent
  def sent
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.name.blank? && @document.image.nil?
        @document.immigration_case.update(status: ImmigrationCase.statuses.keys[2])
        @document.immigration_case.update(sent_date: params[:document][:immigration_case][:sent_date])
        format.html { redirect_to request.referer || foreign_national_url(params[immigration_case_id]), notice: "Marked as Sent" }
      elsif @document.save
        @document.immigration_case.update(status: ImmigrationCase.statuses.keys[2])
        @document.immigration_case.update(sent_date: params[:document][:immigration_case][:sent_date])
        format.html { redirect_to request.referer || foreign_national_url(params[immigration_case_id]), notice: "Document was successfully created. Marked as Sent" }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { redirect_to request.referer || foreign_national_url(params[immigration_case_id]), status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  #add receipt document add receipt number and date then change status to received by gov
  def add_receipt
    @document = Document.new(document_params)
    # delete commented out code
    #img = RTesseract.new(@document.image.path)
    #txt = img.to_s
    
    respond_to do |format|
      if @document.extracted_text.blank?
        format.html { redirect_to request.referer || foreign_national_url(params[immigration_case_id]), status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      elsif @document.save
        @document.immigration_case.update(status: ImmigrationCase.statuses.keys[3])
        @document.immigration_case.update(received_date: params[:document][:immigration_case][:received_date])
        @document.immigration_case.update(receipt_number: params[:document][:extracted_text])
        format.html { redirect_to request.referer || foreign_national_url(params[immigration_case_id]), notice: "Document was successfully created. Added Receipt" }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render redirect_to request.referer || foreign_national_url(params[immigration_case_id]), status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  #change case status to sent then upload doc and add dates
  def approved
    @document = Document.new(document_params)
    respond_to do |format|
      if  @document.save
        # this logic should be in the model or a service
        ####
        @document.immigration_case.update(status: ImmigrationCase.statuses.keys[5])
        @document.immigration_case.update(approval_date: params[:document][:immigration_case][:approval_date])
        @document.immigration_case.update(expiration_date: params[:document][:immigration_case][:expiration_date])
        if @document.immigration_case.case_type == ImmigrationCase.case_types.keys[1]
          @document.immigration_case.fn.update(status: ForeignNational.statuses.keys[3])
        end
        if @document.immigration_case.case_type == ImmigrationCase.case_types.keys[5]
          @document.immigration_case.fn.update(status: ForeignNational.statuses.keys[4])
        end
        #####
        format.html { redirect_to request.referer || foreign_national_url(params[immigration_case_id]), notice: "Document was successfully created. Case Approved" }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render redirect_to request.referer || foreign_national_url(params[immigration_case_id]), status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1 or /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to document_url(@document), notice: "Document was successfully updated." }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1 or /documents/1.json
  def destroy
    id = @document.immigration_case.id
    @document.destroy

    respond_to do |format|
      format.html { redirect_to immigration_case_path(id), notice: "Document was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_document
    @document = Document.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def document_params
    params.require(:document).permit(:immigration_case_id, :name, :image, :extracted_text, :uploader_id, immigration_case_attributes: [:sent_date, :approval_date, :expiration_date])
  end
end

app/views/documents/_approved_form.html.erb
<%= form_with(model: document, url: approved_documents_path, method: :post, class: "needs-validation", novalidate: true, multipart: true) do |form| %>
  <% if document.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading">Validation Error!</h4>
      <ul>
        <% document.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :immigration_case_id, value: immigration_case_id %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label", style: "display: block" %>
    <%= form.text_field :name, value: "Approval Notice", class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :image, class: "form-label", style: "display: block" %>
    <%= form.file_field :image, class: "form-control" %>
  </div>

  <%= form.hidden_field :uploader_id, value: current_user.id %>

  <%= form.fields_for :immigration_case, document.build_immigration_case do |immigration_case_form| %>
    <div class="mb-3">
      <%= immigration_case_form.label :approval_date, "Approved Date", class: "form-label", style: "display: block" %>
      <%= immigration_case_form.date_field :approval_date, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= immigration_case_form.label :expiration_date, "Expiration Date", class: "form-label", style: "display: block" %>
      <%= immigration_case_form.date_field :expiration_date, class: "form-control" %>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/documents/_document.html.erb
<div id="<%= dom_id document %>">
  <p>
    <strong>Case:</strong>
    <%= document.immigration_case_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= document.name %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= document.image %>
  </p>

  <p>
    <strong>Extracted text:</strong>
    <%= document.extracted_text %>
  </p>

  <p>
    <strong>Uploader:</strong>
    <%= document.uploader_id %>
  </p>

</div>

app/views/documents/_form.html.erb
<%= form_with(model: document, class: "needs-validation", novalidate: true) do |form| %>
  <% if document.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h2 class="alert-heading"><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
        <% document.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :immigration_case_id, value: immigration_case_id %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label", style: "display: block" %>
    <%= form.text_field :name, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :image, class: "form-label", style: "display: block" %>
    <%= form.file_field :image, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :extracted_text, class: "form-label", style: "display: block" %>
    <%= form.text_field :extracted_text, class: "form-control" %>
  </div>

  <%= form.hidden_field :uploader_id, value: current_user.id %>

  <div class="mb-3">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/documents/_receipt_form.html.erb
<%= form_with(model: document, url: add_receipt_documents_path, method: :post, class: "needs-validation", novalidate: true, multipart: true) do |form| %>
  <% if document.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading">Validation Error!</h4>
      <ul>
        <% document.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :immigration_case_id, value: immigration_case_id %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, value: "Receipt Notice", class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :image, class: "form-label", style: "display: block" %>
    <%= form.file_field :image, class: "form-control", id: "image-input" %>
  </div>

  <div class="mb-3">
    <%= form.label :extracted_text, "Receipt Number", class: "form-label", style: "display: block" %>
    <%= form.text_field :extracted_text, class: "form-control" , id: "document_extracted_text"%>
  </div>

  <%= form.hidden_field :uploader_id, value: current_user.id %>

  <%= form.fields_for :immigration_case, document.build_immigration_case do |immigration_case_form| %>
    <div class="mb-3">
      <%= immigration_case_form.label :received_date, "Received Date", class: "form-label", style: "display: block" %>
      <%= immigration_case_form.date_field :received_date, class: "form-control", id: "document_immigration_case_attributes_received_date" %>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

<script>
  $(document).ready(function () {
  // Add an event listener for the file input change event
  $("#image-input").change(function () {
    // Get the selected file
    var file = this.files[0];

    // Check if a file is selected
    if (file) {
      // Create a FormData object and append the file to it
      var formData = new FormData();
      formData.append('image', file);

      // Make an AJAX request to your Rails controller action
      $.ajax({
        type: 'POST',
        url: '/documents/extract_text', // Replace with your actual route
        data: formData,
        processData: false,
        contentType: false,
        success: function (data) {
          console.log("Data received from the server:", data);
          // Update the value of the extracted_text field
          if (data.receipt_number) {
            $("#document_extracted_text").val(data.receipt_number);
          } else {
            console.log("No receipt_number in the data.");
            // Handle missing receipt_number
          }

          // Update the value of the received_date field
          if (data.notice_date) {
            $("#document_immigration_case_attributes_received_date").val(data.notice_date);
          } else {
            console.log("No notice_date in the data.");
            // Handle missing notice_date
          }
        },
        error: function (error) {
          console.error("Error:", error);
          // Handle errors more explicitly if needed
        }
      });
    }
  });
});

</script>

app/views/documents/_sent_form.html.erb
<%= form_with(model: document, url: sent_documents_path, method: :post, class: "needs-validation", novalidate: true, multipart: true) do |form| %>
  <% if document.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading">Validation Error!</h4>
      <ul>
        <% document.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :immigration_case_id, value: immigration_case_id %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label", style: "display: block" %>
    <%= form.text_field :name, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :image, class: "form-label", style: "display: block" %>
    <%= form.file_field :image, class: "form-control" %>
  </div>

  <%= form.hidden_field :uploader_id, value: current_user.id %>

  <%= form.fields_for :immigration_case, document.build_immigration_case do |immigration_case_form| %>
    <div class="mb-3">
      <%= immigration_case_form.label :sent_date, "Sent Date", class: "form-label", style: "display: block" %>
      <%= immigration_case_form.date_field :sent_date, class: "form-control" %>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render "form", document: @document %>

<br>

<div>
  <%= link_to "Show this document", @document %> |
  <%= link_to "Back to documents", documents_path %>
</div>

app/views/documents/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Documents</h1>

<div id="documents">
  <% @documents.each do |document| %>
    <%= render document %>
    <p>
      <%= link_to "Show this document", document %>
    </p>
  <% end %>
</div>

<%= link_to "New document", new_document_path %>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render "form", document: @document %>

<br>

<div>
  <%= link_to "Back to documents", documents_path %>
</div>

app/views/documents/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @document %>

<div>
  <%= link_to "Edit this document", edit_document_path(@document) %> |
  <%= link_to "Back to documents", documents_path %>

  <%= button_to "Destroy this document", @document, method: :delete %>
</div>