config/routes.rb
Rails.application.routes.draw do
  resources :documents do
    post 'sent', on: :collection
    post 'add_receipt', on: :collection
    post 'approved', on: :collection
    post 'extract_text', on: :collection

  end
  resources :immigration_cases
  resources :foreign_nationals
  resources :accounts 
  devise_for :users
  resources :accesses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/search', to: 'application#search', as: :search

  # Defines the root path route ("/")

  root "accounts#index"

end
 

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id         :bigint           not null, primary key
#  name       :citext
#  notes      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Account < ApplicationRecord
  has_many :cases, class_name: "ImmigrationCase"

  has_many :accesses
  has_many :users, through: :accesses
  has_many :foreign_nationals
  accepts_nested_attributes_for :accesses
  def account_params
    params.require(:account).permit(:name, :notes, access_attributes: [:role])
  end

  def self.ransackable_attributes(auth_object = nil)
    ["id", "name", "notes"]
  end
  def self.ransackable_associations(auth_object = nil)
    [ "foreign_nationals" ]
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[ show edit update destroy ]

  # GET /accounts or /accounts.json
  def index
    @accounts = if current_user.admin?
      @q = Account.ransack(params[:q])
      @accounts = @q.result
    else
      current_user.accounts
    end
    
  end



  # GET /accounts/1 or /accounts/1.json
  def show
    @account = Account.find(params[:id])
    @account_id = @account.id

  end

  # GET /accounts/new
  def new
    @account = Account.new

  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts or /accounts.json
  def create
    @account = Account.new(account_params)
      if current_user.admin == true
        role = 0
      end
    @access = Access.create(account: @account, user: current_user, role: role)
    respond_to do |format|
      if @account.save
        format.html { redirect_to account_url(@account), notice: "Account was successfully created." }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to account_url(@account), notice: "Account was successfully updated." }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url, notice: "Account was successfully destroyed." }
      format.json { head :no_content }
    end
  end

 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:name, :notes, :username_cont)
    end

    def pass_fn_id(id)
      @fn_id = id
    end
end

app/views/accounts/_account.html.erb
<div id="<%= dom_id account %>">

  <div class="col-md-6">
    <h2><%= account.name %> (<%= account.id%>)</h2>

  </div>

</div>

<hr>
<div style="display: flex; justify-content: space-between; align-items: baseline;">
  <p>
    <strong>Notes:</strong>
    <%= account.notes %>
  </p>
  <% if account.accesses[0] != nil %>
    <p>
      <strong>Role:</strong>
      <%= account.accesses[0].role %>
    </p>
  <% end %>
</div>

app/views/accounts/_account_cases.html.erb
<div class="card">
 <div class="card-header position-relative" style="transition: background-color 0.3s ease; background-color: #fff;" onmouseover="this.style.backgroundColor='rgba(89, 7, 162, .7)'" onmouseout="this.style.backgroundColor='#fff'">    <strong style= " margin-left: 15px;">
       <%= link_to immigration_case.case_type, immigration_case_path(immigration_case.id), class: "stretched-link", style: "color: inherit; text-decoration: none;  font-size: 18px;"  %>
    </strong>
  </div>
  <div class="card-body" style="text-align: center;">
    <h6 class="card-title">Special title treatment</h6>
    
  </div>
</div>

app/views/accounts/_account_fns.html.erb
<div class="card" style="margin-top: 10px; margin-bottom: 10px;">
  <div class="card-header position-relative" style="transition: background-color 0.3s ease; background-color: #fff;" onmouseover="this.style.backgroundColor='rgba(89, 7, 162, .7)'" onmouseout="this.style.backgroundColor='#fff'">
    <div style="display: flex; justify-content: space-between; align-items: baseline; ">
      <h5> 
        <%= link_to fn.name.capitalize(), foreign_national_path(fn.id), class: "stretched-link", style: "color: inherit; text-decoration: none;  font-size: 20px; display: block;"  %>
      </h5>

      <h5><%= fn.status%></h5>
    </div>
  </div>
  <div class="card-body"  >

    <% fn.immigration_cases.each do |immigration_case| %>

      <div class= "col-md-15 offset-md-0" style="padding: 10px">
        <%= render "shared/cases", immigration_case: immigration_case%>
      </div>
 
    <% end %>
    <!-- This toggles modal in shared/new_case that loads an immigration case form. -->

    <%= link_to "#", 
              data: { toggle: "modal", target: "#ImmigrationCaseModal#{fn.id}", fn: fn }, 
              class: "btn btn-light d-flex justify-content-between align-items-baseline ms-auto", 
              style: "width: 40px; text-decoration: none; color: #000;",
              onmouseover: "this.style.backgroundColor='#9205C4';",
              onmouseout: "this.style.backgroundColor='transparent';" do %>
      <i class="fas fa-plus-square"></i>

    <% end %>

  </div>


  <%= render "shared/new_case", fn: fn.id %>
     
 
</div>

app/views/accounts/_account_new_case.html.erb
<!-- Modal -->
<div class="modal fade" id="ImmigrationCaseModal<%=fn%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add New Case</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      
    
        <%= render 'immigration_cases/form', immigration_case: ImmigrationCase.new, foreign_nationals_id: fn%>
        
      </div>
    </div>
  </div>
</div>
 

app/views/accounts/_account_new_fn.html.erb
<!-- Modal -->
<div class="modal fade" id="foreignNationalModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add Foreign National</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       <%= render 'foreign_nationals/form', foreign_national: ForeignNational.new, account_id: params[:account_id] %>
       
      </div>
    </div>
  </div>
</div>

app/views/accounts/_account_side_button.html.erb
<div class="position-fixed bottom-0 start-0">
  <button class="btn btn-light" id="dropdownUser3" data-bs-toggle="dropdown" aria-expanded="false" style="background-color: #9205C4">
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-power" viewBox="0 0 16 16">
      <path d="M7.5 1v7h1V1h-1z"/>
      <path d="M3 8.812a4.999 4.999 0 0 1 2.578-4.375l-.485-.874A6 6 0 1 0 11 3.616l-.501.865A5 5 0 1 1 3 8.812z"/>
    </svg>
  </button>
  <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser3">

    <li><%= link_to "Add Foreign National", "#", class: "dropdown-item", data: { toggle: "modal", target: "#foreignNationalModal",  account_id: params[:account_id]  } %></li>
   
    <li><%= link_to "Edit account", edit_account_path(@account), class: "dropdown-item" %></li>
    
    <li><hr class="dropdown-divider"></li>
    <li><%= button_to "Destroy this account", @account, method: :delete,  class: "dropdown-item", style: "color: #FD0404" %></li>
   
  </ul>

</div>
<%= render "accounts/account_new_fn" %>

app/views/accounts/_form.html.erb
<%= form_with(model: account) do |form| %>
  <% if account.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% account.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :notes, style: "display: block" %>
    <%= form.text_field :notes %>
  </div>
  <hr>


  <div style= "padding-top: 10px">
    <%= form.submit "Save" %>
  </div>


<% end %>

app/views/accounts/edit.html.erb
<div class = "container">
<h1>Editing account</h1>


<%= render "form", account: @account %>

<br>

<div>
  <%= link_to "Show this account", @account %> |
  <%= link_to "Back to accounts", accounts_path %>
</div>

</div>

app/views/accounts/index.html.erb
<div class="row" style="margin: 0,auto;" >
  <% @accounts.each do |account| %>
    <div class="col mx-auto" style= "margin: 20px;  display: flex;
  justify-content: space-around;">
      <div class="card mb-2" style="width: 18rem;
     " id="accounts", >
        <div class="card-header" style="display: flex; justify-content: space-between;">
          <span style="margin-right: auto;"><%= account.name %></span>
          <span style="margin-left: auto;">ID: <%= account.id %></span>
        </div>
        <div class="card-body">
          <p class="card-text"><%= account.notes %></p>
        </div>
            <%= link_to "Show Account", account, class: "btn", style: "background-color: rgba(89, 7, 162, 0.7);" %>
      </div>
    </div>
  <% end %>
</div>

app/views/accounts/new.html.erb
<div class="container">
<h1>New account</h1>

<%= render "form", account: @account %>

<br>

<div>
  <%= link_to "Back to accounts", accounts_path %>
</div>

</div>

app/views/accounts/show.html.erb
<div class="d-flex">



<div class="col-md-10 offset-md-1">

  <%= render @account %>

  <% @account.foreign_nationals.each do |fn| %>

    <%= render "account_fns", fn: fn %>

  <% end %>
</div>
<%= render "account_side_button"  %>

</div>